---
- name: Create user
  hosts:
    vms
  vars_prompt:
  become: yes
  become_method: sudo
  tasks:
    - name: Add the user serveradm
      ansible.builtin.user:
        name: serveradm
        password: '$6$w9chdQxJ7WA7b$UkC2msaSeQRmSKWwILSdfBBZRHk8/t63y1.C1w8a0Aj9Wm0iryKcluZ3Hoz./u6C5ynOsC6mWvsaTrq2zMM9j1'
        comment: serveradm
        groups: sudo
        createhome: yes
        home: /home/serveradm
        shell: /bin/bash
        append: yes
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa
