- hosts: localhost
  gather_facts: no
  vars_prompt:
  - name: target_host
    prompt: please enter the target hosts
    private: no
  tasks:
    - add_host:
        name: "{{ target_host }}"
        groups: dynamically_created_hosts
--- 
- hosts: dynamically_created_hosts
  tasks:
  - debug: msg="do things on target host here"

# tasks file for zabbix-agent
- name: Install and configure packages
  hosts: localhost
  become: yes
  become_method: sudo
  tasks:
    - name: Add zabbix-agent from deb
      shell: wget https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-1+ubuntu20.04_all.deb

    - name: dpkg install zabbix
      shell: dpkg -i zabbix-release_6.0-1+ubuntu20.04_all.deb

    - name: Install zabbix-agent
      apt:
        update_cache: yes
        pkg: zabbix-agent
        state: present