- name: Upload ssh key
  hosts: vms
  become: yes
  become_method: sudo 
  tasks:
    - name: Set authorized key took from file
      authorized_key:
        user: serveradm
        state: present
        key: "{{ lookup('file', '/home/serveradm/id_rsa_nzk.pub') }}"

    - name: Restart sshd
      service:
        name: sshd
        state: restarted