version: "3"
services:
  wiki:
    image: ghcr.io/requarks/wiki:2
    environment:
      DB_TYPE: postgres
      DB_HOST: 192.168.100
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
      HA_ACTIVE: 1
    restart: unless-stopped
    ports:
      - "80:3000"

volumes:
  db-data: